{-# LANGUAGE DeriveGeneric     #-}
{-# LANGUAGE DeriveAnyClass    #-}
{-# LANGUAGE DataKinds         #-}
{-# LANGUAGE GADTs             #-}
{-# LANGUAGE TypeApplications  #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -fno-warn-unused-imports #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing #-}
{-# OPTIONS_GHC -fno-warn-unused-matches #-}

-- | Generated by Haskell protocol buffer compiler. DO NOT EDIT!
module HStream.Broker.API where
import qualified Prelude as Hs
import qualified Proto3.Suite.Class as HsProtobuf
import qualified Proto3.Suite.DotProto as HsProtobuf
import qualified Proto3.Suite.JSONPB as HsJSONPB
import Proto3.Suite.JSONPB ((.=), (.:))
import qualified Proto3.Suite.Types as HsProtobuf
import qualified Proto3.Wire as HsProtobuf
import qualified Control.Applicative as Hs
import Control.Applicative ((<*>), (<|>), (<$>))
import qualified Control.DeepSeq as Hs
import qualified Control.Monad as Hs
import qualified Data.ByteString as Hs
import qualified Data.Coerce as Hs
import qualified Data.Int as Hs (Int16, Int32, Int64)
import qualified Data.List.NonEmpty as Hs (NonEmpty(..))
import qualified Data.Map as Hs (Map, mapKeysMonotonic)
import qualified Data.Proxy as Proxy
import qualified Data.String as Hs (fromString)
import qualified Data.Text.Lazy as Hs (Text)
import qualified Data.Vector as Hs (Vector)
import qualified Data.Word as Hs (Word16, Word32, Word64)
import qualified GHC.Enum as Hs
import qualified GHC.Generics as Hs
import qualified Unsafe.Coerce as Hs
import Network.GRPC.HighLevel.Generated as HsGRPC
import Network.GRPC.HighLevel.Client as HsGRPC
import Network.GRPC.HighLevel.Server as HsGRPC hiding (serverLoop)
import Network.GRPC.HighLevel.Server.Unregistered as HsGRPC
       (serverLoop)
 
data HStreamBroker request
     response = HStreamBroker{hstreamBrokerConnect ::
                              request 'HsGRPC.Normal HStream.Broker.API.CommandConnect
                                HStream.Broker.API.CommandConnected
                                ->
                                Hs.IO
                                  (response 'HsGRPC.Normal HStream.Broker.API.CommandConnected),
                              hstreamBrokerCreateProducer ::
                              request 'HsGRPC.Normal HStream.Broker.API.CommandProducer
                                HStream.Broker.API.CommandProducerSuccess
                                ->
                                Hs.IO
                                  (response 'HsGRPC.Normal
                                     HStream.Broker.API.CommandProducerSuccess),
                              hstreamBrokerSendRecord ::
                              request 'HsGRPC.Normal HStream.Broker.API.CommandSend
                                HStream.Broker.API.CommandSendSuccess
                                ->
                                Hs.IO
                                  (response 'HsGRPC.Normal HStream.Broker.API.CommandSendSuccess),
                              hstreamBrokerCloseProducer ::
                              request 'HsGRPC.Normal HStream.Broker.API.CommandCloseProducer
                                HStream.Broker.API.CommandSuccess
                                ->
                                Hs.IO (response 'HsGRPC.Normal HStream.Broker.API.CommandSuccess),
                              hstreamBrokerSubscribe ::
                              request 'HsGRPC.Normal HStream.Broker.API.CommandSubscribe
                                HStream.Broker.API.CommandSubscribeSuccess
                                ->
                                Hs.IO
                                  (response 'HsGRPC.Normal
                                     HStream.Broker.API.CommandSubscribeSuccess),
                              hstreamBrokerReceiveRecords ::
                              request 'HsGRPC.ServerStreaming HStream.Broker.API.CommandReceive
                                HStream.Broker.API.CommandRecord
                                ->
                                Hs.IO
                                  (response 'HsGRPC.ServerStreaming
                                     HStream.Broker.API.CommandRecord),
                              hstreamBrokerSendAck ::
                              request 'HsGRPC.Normal HStream.Broker.API.CommandAck
                                HStream.Broker.API.CommandSuccess
                                ->
                                Hs.IO (response 'HsGRPC.Normal HStream.Broker.API.CommandSuccess),
                              hstreamBrokerCloseConsumer ::
                              request 'HsGRPC.Normal HStream.Broker.API.CommandCloseConsumer
                                HStream.Broker.API.CommandSuccess
                                ->
                                Hs.IO (response 'HsGRPC.Normal HStream.Broker.API.CommandSuccess)}
              deriving Hs.Generic
 
hstreamBrokerServer ::
                      HStreamBroker HsGRPC.ServerRequest HsGRPC.ServerResponse ->
                        HsGRPC.ServiceOptions -> Hs.IO ()
hstreamBrokerServer
  HStreamBroker{hstreamBrokerConnect = hstreamBrokerConnect,
                hstreamBrokerCreateProducer = hstreamBrokerCreateProducer,
                hstreamBrokerSendRecord = hstreamBrokerSendRecord,
                hstreamBrokerCloseProducer = hstreamBrokerCloseProducer,
                hstreamBrokerSubscribe = hstreamBrokerSubscribe,
                hstreamBrokerReceiveRecords = hstreamBrokerReceiveRecords,
                hstreamBrokerSendAck = hstreamBrokerSendAck,
                hstreamBrokerCloseConsumer = hstreamBrokerCloseConsumer}
  (ServiceOptions serverHost serverPort useCompression
     userAgentPrefix userAgentSuffix initialMetadata sslConfig logger
     serverMaxReceiveMessageLength)
  = (HsGRPC.serverLoop
       HsGRPC.defaultOptions{HsGRPC.optNormalHandlers =
                               [(HsGRPC.UnaryHandler
                                   (HsGRPC.MethodName "/hstream.broker.HStreamBroker/Connect")
                                   (HsGRPC.convertGeneratedServerHandler hstreamBrokerConnect)),
                                (HsGRPC.UnaryHandler
                                   (HsGRPC.MethodName
                                      "/hstream.broker.HStreamBroker/CreateProducer")
                                   (HsGRPC.convertGeneratedServerHandler
                                      hstreamBrokerCreateProducer)),
                                (HsGRPC.UnaryHandler
                                   (HsGRPC.MethodName "/hstream.broker.HStreamBroker/SendRecord")
                                   (HsGRPC.convertGeneratedServerHandler hstreamBrokerSendRecord)),
                                (HsGRPC.UnaryHandler
                                   (HsGRPC.MethodName "/hstream.broker.HStreamBroker/CloseProducer")
                                   (HsGRPC.convertGeneratedServerHandler
                                      hstreamBrokerCloseProducer)),
                                (HsGRPC.UnaryHandler
                                   (HsGRPC.MethodName "/hstream.broker.HStreamBroker/Subscribe")
                                   (HsGRPC.convertGeneratedServerHandler hstreamBrokerSubscribe)),
                                (HsGRPC.UnaryHandler
                                   (HsGRPC.MethodName "/hstream.broker.HStreamBroker/SendAck")
                                   (HsGRPC.convertGeneratedServerHandler hstreamBrokerSendAck)),
                                (HsGRPC.UnaryHandler
                                   (HsGRPC.MethodName "/hstream.broker.HStreamBroker/CloseConsumer")
                                   (HsGRPC.convertGeneratedServerHandler
                                      hstreamBrokerCloseConsumer))],
                             HsGRPC.optClientStreamHandlers = [],
                             HsGRPC.optServerStreamHandlers =
                               [(HsGRPC.ServerStreamHandler
                                   (HsGRPC.MethodName
                                      "/hstream.broker.HStreamBroker/ReceiveRecords")
                                   (HsGRPC.convertGeneratedServerWriterHandler
                                      hstreamBrokerReceiveRecords))],
                             HsGRPC.optBiDiStreamHandlers = [], optServerHost = serverHost,
                             optServerPort = serverPort, optUseCompression = useCompression,
                             optUserAgentPrefix = userAgentPrefix,
                             optUserAgentSuffix = userAgentSuffix,
                             optInitialMetadata = initialMetadata, optSSLConfig = sslConfig,
                             optLogger = logger,
                             optMaxReceiveMessageLength = serverMaxReceiveMessageLength})
 
hstreamBrokerClient ::
                      HsGRPC.Client ->
                        Hs.IO (HStreamBroker HsGRPC.ClientRequest HsGRPC.ClientResult)
hstreamBrokerClient client
  = (Hs.pure HStreamBroker) <*>
      ((Hs.pure (HsGRPC.clientRequest client)) <*>
         (HsGRPC.clientRegisterMethod client
            (HsGRPC.MethodName "/hstream.broker.HStreamBroker/Connect")))
      <*>
      ((Hs.pure (HsGRPC.clientRequest client)) <*>
         (HsGRPC.clientRegisterMethod client
            (HsGRPC.MethodName
               "/hstream.broker.HStreamBroker/CreateProducer")))
      <*>
      ((Hs.pure (HsGRPC.clientRequest client)) <*>
         (HsGRPC.clientRegisterMethod client
            (HsGRPC.MethodName "/hstream.broker.HStreamBroker/SendRecord")))
      <*>
      ((Hs.pure (HsGRPC.clientRequest client)) <*>
         (HsGRPC.clientRegisterMethod client
            (HsGRPC.MethodName "/hstream.broker.HStreamBroker/CloseProducer")))
      <*>
      ((Hs.pure (HsGRPC.clientRequest client)) <*>
         (HsGRPC.clientRegisterMethod client
            (HsGRPC.MethodName "/hstream.broker.HStreamBroker/Subscribe")))
      <*>
      ((Hs.pure (HsGRPC.clientRequest client)) <*>
         (HsGRPC.clientRegisterMethod client
            (HsGRPC.MethodName
               "/hstream.broker.HStreamBroker/ReceiveRecords")))
      <*>
      ((Hs.pure (HsGRPC.clientRequest client)) <*>
         (HsGRPC.clientRegisterMethod client
            (HsGRPC.MethodName "/hstream.broker.HStreamBroker/SendAck")))
      <*>
      ((Hs.pure (HsGRPC.clientRequest client)) <*>
         (HsGRPC.clientRegisterMethod client
            (HsGRPC.MethodName "/hstream.broker.HStreamBroker/CloseConsumer")))
 
data CommandConnect = CommandConnect{commandConnectClientVersion ::
                                     Hs.Text,
                                     commandConnectProtocolVersion :: Hs.Int32}
                    deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic, Hs.NFData)
 
instance HsProtobuf.Named CommandConnect where
        nameOf _ = (Hs.fromString "CommandConnect")
 
instance HsProtobuf.HasDefault CommandConnect
 
instance HsProtobuf.Message CommandConnect where
        encodeMessage _
          CommandConnect{commandConnectClientVersion =
                           commandConnectClientVersion,
                         commandConnectProtocolVersion = commandConnectProtocolVersion}
          = (Hs.mconcat
               [(HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 1)
                   commandConnectClientVersion),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 2)
                   commandConnectProtocolVersion)])
        decodeMessage _
          = (Hs.pure CommandConnect) <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 1))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 2))
        dotProto _
          = [(HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 1)
                (HsProtobuf.Prim HsProtobuf.String)
                (HsProtobuf.Single "client_version")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 2)
                (HsProtobuf.Prim HsProtobuf.Int32)
                (HsProtobuf.Single "protocol_version")
                []
                "")]
 
instance HsJSONPB.ToJSONPB CommandConnect where
        toJSONPB (CommandConnect f1 f2)
          = (HsJSONPB.object
               ["client_version" .= f1, "protocol_version" .= f2])
        toEncodingPB (CommandConnect f1 f2)
          = (HsJSONPB.pairs
               ["client_version" .= f1, "protocol_version" .= f2])
 
instance HsJSONPB.FromJSONPB CommandConnect where
        parseJSONPB
          = (HsJSONPB.withObject "CommandConnect"
               (\ obj ->
                  (Hs.pure CommandConnect) <*> obj .: "client_version" <*>
                    obj .: "protocol_version"))
 
instance HsJSONPB.ToJSON CommandConnect where
        toJSON = HsJSONPB.toAesonValue
        toEncoding = HsJSONPB.toAesonEncoding
 
instance HsJSONPB.FromJSON CommandConnect where
        parseJSON = HsJSONPB.parseJSONPB
 
instance HsJSONPB.ToSchema CommandConnect where
        declareNamedSchema _
          = do let declare_client_version = HsJSONPB.declareSchemaRef
               commandConnectClientVersion <- declare_client_version Proxy.Proxy
               let declare_protocol_version = HsJSONPB.declareSchemaRef
               commandConnectProtocolVersion <- declare_protocol_version
                                                  Proxy.Proxy
               let _ = Hs.pure CommandConnect <*>
                         HsJSONPB.asProxy declare_client_version
                         <*> HsJSONPB.asProxy declare_protocol_version
               Hs.return
                 (HsJSONPB.NamedSchema{HsJSONPB._namedSchemaName =
                                         Hs.Just "CommandConnect",
                                       HsJSONPB._namedSchemaSchema =
                                         Hs.mempty{HsJSONPB._schemaParamSchema =
                                                     Hs.mempty{HsJSONPB._paramSchemaType =
                                                                 Hs.Just HsJSONPB.SwaggerObject},
                                                   HsJSONPB._schemaProperties =
                                                     HsJSONPB.insOrdFromList
                                                       [("client_version",
                                                         commandConnectClientVersion),
                                                        ("protocol_version",
                                                         commandConnectProtocolVersion)]}})
 
data CommandConnected = CommandConnected{commandConnectedServerVersion
                                         :: Hs.Text,
                                         commandConnectedProtocolVersion :: Hs.Int32}
                      deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic, Hs.NFData)
 
instance HsProtobuf.Named CommandConnected where
        nameOf _ = (Hs.fromString "CommandConnected")
 
instance HsProtobuf.HasDefault CommandConnected
 
instance HsProtobuf.Message CommandConnected where
        encodeMessage _
          CommandConnected{commandConnectedServerVersion =
                             commandConnectedServerVersion,
                           commandConnectedProtocolVersion = commandConnectedProtocolVersion}
          = (Hs.mconcat
               [(HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 1)
                   commandConnectedServerVersion),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 2)
                   commandConnectedProtocolVersion)])
        decodeMessage _
          = (Hs.pure CommandConnected) <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 1))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 2))
        dotProto _
          = [(HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 1)
                (HsProtobuf.Prim HsProtobuf.String)
                (HsProtobuf.Single "server_version")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 2)
                (HsProtobuf.Prim HsProtobuf.Int32)
                (HsProtobuf.Single "protocol_version")
                []
                "")]
 
instance HsJSONPB.ToJSONPB CommandConnected where
        toJSONPB (CommandConnected f1 f2)
          = (HsJSONPB.object
               ["server_version" .= f1, "protocol_version" .= f2])
        toEncodingPB (CommandConnected f1 f2)
          = (HsJSONPB.pairs
               ["server_version" .= f1, "protocol_version" .= f2])
 
instance HsJSONPB.FromJSONPB CommandConnected where
        parseJSONPB
          = (HsJSONPB.withObject "CommandConnected"
               (\ obj ->
                  (Hs.pure CommandConnected) <*> obj .: "server_version" <*>
                    obj .: "protocol_version"))
 
instance HsJSONPB.ToJSON CommandConnected where
        toJSON = HsJSONPB.toAesonValue
        toEncoding = HsJSONPB.toAesonEncoding
 
instance HsJSONPB.FromJSON CommandConnected where
        parseJSON = HsJSONPB.parseJSONPB
 
instance HsJSONPB.ToSchema CommandConnected where
        declareNamedSchema _
          = do let declare_server_version = HsJSONPB.declareSchemaRef
               commandConnectedServerVersion <- declare_server_version Proxy.Proxy
               let declare_protocol_version = HsJSONPB.declareSchemaRef
               commandConnectedProtocolVersion <- declare_protocol_version
                                                    Proxy.Proxy
               let _ = Hs.pure CommandConnected <*>
                         HsJSONPB.asProxy declare_server_version
                         <*> HsJSONPB.asProxy declare_protocol_version
               Hs.return
                 (HsJSONPB.NamedSchema{HsJSONPB._namedSchemaName =
                                         Hs.Just "CommandConnected",
                                       HsJSONPB._namedSchemaSchema =
                                         Hs.mempty{HsJSONPB._schemaParamSchema =
                                                     Hs.mempty{HsJSONPB._paramSchemaType =
                                                                 Hs.Just HsJSONPB.SwaggerObject},
                                                   HsJSONPB._schemaProperties =
                                                     HsJSONPB.insOrdFromList
                                                       [("server_version",
                                                         commandConnectedServerVersion),
                                                        ("protocol_version",
                                                         commandConnectedProtocolVersion)]}})
 
data CommandProducer = CommandProducer{commandProducerTopic ::
                                       Hs.Text,
                                       commandProducerProducerId :: Hs.Word64,
                                       commandProducerProducerName :: Hs.Text}
                     deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic, Hs.NFData)
 
instance HsProtobuf.Named CommandProducer where
        nameOf _ = (Hs.fromString "CommandProducer")
 
instance HsProtobuf.HasDefault CommandProducer
 
instance HsProtobuf.Message CommandProducer where
        encodeMessage _
          CommandProducer{commandProducerTopic = commandProducerTopic,
                          commandProducerProducerId = commandProducerProducerId,
                          commandProducerProducerName = commandProducerProducerName}
          = (Hs.mconcat
               [(HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 1)
                   commandProducerTopic),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 2)
                   commandProducerProducerId),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 3)
                   commandProducerProducerName)])
        decodeMessage _
          = (Hs.pure CommandProducer) <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 1))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 2))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 3))
        dotProto _
          = [(HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 1)
                (HsProtobuf.Prim HsProtobuf.String)
                (HsProtobuf.Single "topic")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 2)
                (HsProtobuf.Prim HsProtobuf.UInt64)
                (HsProtobuf.Single "producer_id")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 3)
                (HsProtobuf.Prim HsProtobuf.String)
                (HsProtobuf.Single "producer_name")
                []
                "")]
 
instance HsJSONPB.ToJSONPB CommandProducer where
        toJSONPB (CommandProducer f1 f2 f3)
          = (HsJSONPB.object
               ["topic" .= f1, "producer_id" .= f2, "producer_name" .= f3])
        toEncodingPB (CommandProducer f1 f2 f3)
          = (HsJSONPB.pairs
               ["topic" .= f1, "producer_id" .= f2, "producer_name" .= f3])
 
instance HsJSONPB.FromJSONPB CommandProducer where
        parseJSONPB
          = (HsJSONPB.withObject "CommandProducer"
               (\ obj ->
                  (Hs.pure CommandProducer) <*> obj .: "topic" <*>
                    obj .: "producer_id"
                    <*> obj .: "producer_name"))
 
instance HsJSONPB.ToJSON CommandProducer where
        toJSON = HsJSONPB.toAesonValue
        toEncoding = HsJSONPB.toAesonEncoding
 
instance HsJSONPB.FromJSON CommandProducer where
        parseJSON = HsJSONPB.parseJSONPB
 
instance HsJSONPB.ToSchema CommandProducer where
        declareNamedSchema _
          = do let declare_topic = HsJSONPB.declareSchemaRef
               commandProducerTopic <- declare_topic Proxy.Proxy
               let declare_producer_id = HsJSONPB.declareSchemaRef
               commandProducerProducerId <- declare_producer_id Proxy.Proxy
               let declare_producer_name = HsJSONPB.declareSchemaRef
               commandProducerProducerName <- declare_producer_name Proxy.Proxy
               let _ = Hs.pure CommandProducer <*> HsJSONPB.asProxy declare_topic
                         <*> HsJSONPB.asProxy declare_producer_id
                         <*> HsJSONPB.asProxy declare_producer_name
               Hs.return
                 (HsJSONPB.NamedSchema{HsJSONPB._namedSchemaName =
                                         Hs.Just "CommandProducer",
                                       HsJSONPB._namedSchemaSchema =
                                         Hs.mempty{HsJSONPB._schemaParamSchema =
                                                     Hs.mempty{HsJSONPB._paramSchemaType =
                                                                 Hs.Just HsJSONPB.SwaggerObject},
                                                   HsJSONPB._schemaProperties =
                                                     HsJSONPB.insOrdFromList
                                                       [("topic", commandProducerTopic),
                                                        ("producer_id", commandProducerProducerId),
                                                        ("producer_name",
                                                         commandProducerProducerName)]}})
 
newtype CommandProducerSuccess = CommandProducerSuccess{commandProducerSuccessProducerName
                                                        :: Hs.Text}
                                 deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic, Hs.NFData)
 
instance HsProtobuf.Named CommandProducerSuccess where
        nameOf _ = (Hs.fromString "CommandProducerSuccess")
 
instance HsProtobuf.HasDefault CommandProducerSuccess
 
instance HsProtobuf.Message CommandProducerSuccess where
        encodeMessage _
          CommandProducerSuccess{commandProducerSuccessProducerName =
                                   commandProducerSuccessProducerName}
          = (Hs.mconcat
               [(HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 1)
                   commandProducerSuccessProducerName)])
        decodeMessage _
          = (Hs.pure CommandProducerSuccess) <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 1))
        dotProto _
          = [(HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 1)
                (HsProtobuf.Prim HsProtobuf.String)
                (HsProtobuf.Single "producer_name")
                []
                "")]
 
instance HsJSONPB.ToJSONPB CommandProducerSuccess where
        toJSONPB (CommandProducerSuccess f1)
          = (HsJSONPB.object ["producer_name" .= f1])
        toEncodingPB (CommandProducerSuccess f1)
          = (HsJSONPB.pairs ["producer_name" .= f1])
 
instance HsJSONPB.FromJSONPB CommandProducerSuccess where
        parseJSONPB
          = (HsJSONPB.withObject "CommandProducerSuccess"
               (\ obj ->
                  (Hs.pure CommandProducerSuccess) <*> obj .: "producer_name"))
 
instance HsJSONPB.ToJSON CommandProducerSuccess where
        toJSON = HsJSONPB.toAesonValue
        toEncoding = HsJSONPB.toAesonEncoding
 
instance HsJSONPB.FromJSON CommandProducerSuccess where
        parseJSON = HsJSONPB.parseJSONPB
 
instance HsJSONPB.ToSchema CommandProducerSuccess where
        declareNamedSchema _
          = do let declare_producer_name = HsJSONPB.declareSchemaRef
               commandProducerSuccessProducerName <- declare_producer_name
                                                       Proxy.Proxy
               let _ = Hs.pure CommandProducerSuccess <*>
                         HsJSONPB.asProxy declare_producer_name
               Hs.return
                 (HsJSONPB.NamedSchema{HsJSONPB._namedSchemaName =
                                         Hs.Just "CommandProducerSuccess",
                                       HsJSONPB._namedSchemaSchema =
                                         Hs.mempty{HsJSONPB._schemaParamSchema =
                                                     Hs.mempty{HsJSONPB._paramSchemaType =
                                                                 Hs.Just HsJSONPB.SwaggerObject},
                                                   HsJSONPB._schemaProperties =
                                                     HsJSONPB.insOrdFromList
                                                       [("producer_name",
                                                         commandProducerSuccessProducerName)]}})
 
data CommandSend = CommandSend{commandSendProducerId :: Hs.Word64,
                               commandSendPayload :: Hs.ByteString}
                 deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic, Hs.NFData)
 
instance HsProtobuf.Named CommandSend where
        nameOf _ = (Hs.fromString "CommandSend")
 
instance HsProtobuf.HasDefault CommandSend
 
instance HsProtobuf.Message CommandSend where
        encodeMessage _
          CommandSend{commandSendProducerId = commandSendProducerId,
                      commandSendPayload = commandSendPayload}
          = (Hs.mconcat
               [(HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 1)
                   commandSendProducerId),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 2)
                   commandSendPayload)])
        decodeMessage _
          = (Hs.pure CommandSend) <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 1))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 2))
        dotProto _
          = [(HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 1)
                (HsProtobuf.Prim HsProtobuf.UInt64)
                (HsProtobuf.Single "producer_id")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 2)
                (HsProtobuf.Prim HsProtobuf.Bytes)
                (HsProtobuf.Single "payload")
                []
                "")]
 
instance HsJSONPB.ToJSONPB CommandSend where
        toJSONPB (CommandSend f1 f2)
          = (HsJSONPB.object ["producer_id" .= f1, "payload" .= f2])
        toEncodingPB (CommandSend f1 f2)
          = (HsJSONPB.pairs ["producer_id" .= f1, "payload" .= f2])
 
instance HsJSONPB.FromJSONPB CommandSend where
        parseJSONPB
          = (HsJSONPB.withObject "CommandSend"
               (\ obj ->
                  (Hs.pure CommandSend) <*> obj .: "producer_id" <*>
                    obj .: "payload"))
 
instance HsJSONPB.ToJSON CommandSend where
        toJSON = HsJSONPB.toAesonValue
        toEncoding = HsJSONPB.toAesonEncoding
 
instance HsJSONPB.FromJSON CommandSend where
        parseJSON = HsJSONPB.parseJSONPB
 
instance HsJSONPB.ToSchema CommandSend where
        declareNamedSchema _
          = do let declare_producer_id = HsJSONPB.declareSchemaRef
               commandSendProducerId <- declare_producer_id Proxy.Proxy
               let declare_payload = HsJSONPB.declareSchemaRef
               commandSendPayload <- declare_payload Proxy.Proxy
               let _ = Hs.pure CommandSend <*>
                         HsJSONPB.asProxy declare_producer_id
                         <*> HsJSONPB.asProxy declare_payload
               Hs.return
                 (HsJSONPB.NamedSchema{HsJSONPB._namedSchemaName =
                                         Hs.Just "CommandSend",
                                       HsJSONPB._namedSchemaSchema =
                                         Hs.mempty{HsJSONPB._schemaParamSchema =
                                                     Hs.mempty{HsJSONPB._paramSchemaType =
                                                                 Hs.Just HsJSONPB.SwaggerObject},
                                                   HsJSONPB._schemaProperties =
                                                     HsJSONPB.insOrdFromList
                                                       [("producer_id", commandSendProducerId),
                                                        ("payload", commandSendPayload)]}})
 
data CommandSendSuccess = CommandSendSuccess{commandSendSuccessProducerId
                                             :: Hs.Word64,
                                             commandSendSuccessSequenceId :: Hs.Word64}
                        deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic, Hs.NFData)
 
instance HsProtobuf.Named CommandSendSuccess where
        nameOf _ = (Hs.fromString "CommandSendSuccess")
 
instance HsProtobuf.HasDefault CommandSendSuccess
 
instance HsProtobuf.Message CommandSendSuccess where
        encodeMessage _
          CommandSendSuccess{commandSendSuccessProducerId =
                               commandSendSuccessProducerId,
                             commandSendSuccessSequenceId = commandSendSuccessSequenceId}
          = (Hs.mconcat
               [(HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 1)
                   commandSendSuccessProducerId),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 2)
                   commandSendSuccessSequenceId)])
        decodeMessage _
          = (Hs.pure CommandSendSuccess) <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 1))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 2))
        dotProto _
          = [(HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 1)
                (HsProtobuf.Prim HsProtobuf.UInt64)
                (HsProtobuf.Single "producer_id")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 2)
                (HsProtobuf.Prim HsProtobuf.UInt64)
                (HsProtobuf.Single "sequence_id")
                []
                "")]
 
instance HsJSONPB.ToJSONPB CommandSendSuccess where
        toJSONPB (CommandSendSuccess f1 f2)
          = (HsJSONPB.object ["producer_id" .= f1, "sequence_id" .= f2])
        toEncodingPB (CommandSendSuccess f1 f2)
          = (HsJSONPB.pairs ["producer_id" .= f1, "sequence_id" .= f2])
 
instance HsJSONPB.FromJSONPB CommandSendSuccess where
        parseJSONPB
          = (HsJSONPB.withObject "CommandSendSuccess"
               (\ obj ->
                  (Hs.pure CommandSendSuccess) <*> obj .: "producer_id" <*>
                    obj .: "sequence_id"))
 
instance HsJSONPB.ToJSON CommandSendSuccess where
        toJSON = HsJSONPB.toAesonValue
        toEncoding = HsJSONPB.toAesonEncoding
 
instance HsJSONPB.FromJSON CommandSendSuccess where
        parseJSON = HsJSONPB.parseJSONPB
 
instance HsJSONPB.ToSchema CommandSendSuccess where
        declareNamedSchema _
          = do let declare_producer_id = HsJSONPB.declareSchemaRef
               commandSendSuccessProducerId <- declare_producer_id Proxy.Proxy
               let declare_sequence_id = HsJSONPB.declareSchemaRef
               commandSendSuccessSequenceId <- declare_sequence_id Proxy.Proxy
               let _ = Hs.pure CommandSendSuccess <*>
                         HsJSONPB.asProxy declare_producer_id
                         <*> HsJSONPB.asProxy declare_sequence_id
               Hs.return
                 (HsJSONPB.NamedSchema{HsJSONPB._namedSchemaName =
                                         Hs.Just "CommandSendSuccess",
                                       HsJSONPB._namedSchemaSchema =
                                         Hs.mempty{HsJSONPB._schemaParamSchema =
                                                     Hs.mempty{HsJSONPB._paramSchemaType =
                                                                 Hs.Just HsJSONPB.SwaggerObject},
                                                   HsJSONPB._schemaProperties =
                                                     HsJSONPB.insOrdFromList
                                                       [("producer_id",
                                                         commandSendSuccessProducerId),
                                                        ("sequence_id",
                                                         commandSendSuccessSequenceId)]}})
 
newtype CommandCloseProducer = CommandCloseProducer{commandCloseProducerProducerId
                                                    :: Hs.Word64}
                               deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic, Hs.NFData)
 
instance HsProtobuf.Named CommandCloseProducer where
        nameOf _ = (Hs.fromString "CommandCloseProducer")
 
instance HsProtobuf.HasDefault CommandCloseProducer
 
instance HsProtobuf.Message CommandCloseProducer where
        encodeMessage _
          CommandCloseProducer{commandCloseProducerProducerId =
                                 commandCloseProducerProducerId}
          = (Hs.mconcat
               [(HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 1)
                   commandCloseProducerProducerId)])
        decodeMessage _
          = (Hs.pure CommandCloseProducer) <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 1))
        dotProto _
          = [(HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 1)
                (HsProtobuf.Prim HsProtobuf.UInt64)
                (HsProtobuf.Single "producer_id")
                []
                "")]
 
instance HsJSONPB.ToJSONPB CommandCloseProducer where
        toJSONPB (CommandCloseProducer f1)
          = (HsJSONPB.object ["producer_id" .= f1])
        toEncodingPB (CommandCloseProducer f1)
          = (HsJSONPB.pairs ["producer_id" .= f1])
 
instance HsJSONPB.FromJSONPB CommandCloseProducer where
        parseJSONPB
          = (HsJSONPB.withObject "CommandCloseProducer"
               (\ obj -> (Hs.pure CommandCloseProducer) <*> obj .: "producer_id"))
 
instance HsJSONPB.ToJSON CommandCloseProducer where
        toJSON = HsJSONPB.toAesonValue
        toEncoding = HsJSONPB.toAesonEncoding
 
instance HsJSONPB.FromJSON CommandCloseProducer where
        parseJSON = HsJSONPB.parseJSONPB
 
instance HsJSONPB.ToSchema CommandCloseProducer where
        declareNamedSchema _
          = do let declare_producer_id = HsJSONPB.declareSchemaRef
               commandCloseProducerProducerId <- declare_producer_id Proxy.Proxy
               let _ = Hs.pure CommandCloseProducer <*>
                         HsJSONPB.asProxy declare_producer_id
               Hs.return
                 (HsJSONPB.NamedSchema{HsJSONPB._namedSchemaName =
                                         Hs.Just "CommandCloseProducer",
                                       HsJSONPB._namedSchemaSchema =
                                         Hs.mempty{HsJSONPB._schemaParamSchema =
                                                     Hs.mempty{HsJSONPB._paramSchemaType =
                                                                 Hs.Just HsJSONPB.SwaggerObject},
                                                   HsJSONPB._schemaProperties =
                                                     HsJSONPB.insOrdFromList
                                                       [("producer_id",
                                                         commandCloseProducerProducerId)]}})
 
data CommandSubscribe = CommandSubscribe{commandSubscribeTopic ::
                                         Hs.Text,
                                         commandSubscribeSubscription :: Hs.Text,
                                         commandSubscribeSubType ::
                                         HsProtobuf.Enumerated
                                           HStream.Broker.API.CommandSubscribe_SubType,
                                         commandSubscribeConsumerId :: Hs.Word64,
                                         commandSubscribeConsumerName :: Hs.Text}
                      deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic, Hs.NFData)
 
instance HsProtobuf.Named CommandSubscribe where
        nameOf _ = (Hs.fromString "CommandSubscribe")
 
instance HsProtobuf.HasDefault CommandSubscribe
 
instance HsProtobuf.Message CommandSubscribe where
        encodeMessage _
          CommandSubscribe{commandSubscribeTopic = commandSubscribeTopic,
                           commandSubscribeSubscription = commandSubscribeSubscription,
                           commandSubscribeSubType = commandSubscribeSubType,
                           commandSubscribeConsumerId = commandSubscribeConsumerId,
                           commandSubscribeConsumerName = commandSubscribeConsumerName}
          = (Hs.mconcat
               [(HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 1)
                   commandSubscribeTopic),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 2)
                   commandSubscribeSubscription),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 3)
                   commandSubscribeSubType),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 4)
                   commandSubscribeConsumerId),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 5)
                   commandSubscribeConsumerName)])
        decodeMessage _
          = (Hs.pure CommandSubscribe) <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 1))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 2))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 3))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 4))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 5))
        dotProto _
          = [(HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 1)
                (HsProtobuf.Prim HsProtobuf.String)
                (HsProtobuf.Single "topic")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 2)
                (HsProtobuf.Prim HsProtobuf.String)
                (HsProtobuf.Single "subscription")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 3)
                (HsProtobuf.Prim (HsProtobuf.Named (HsProtobuf.Single "SubType")))
                (HsProtobuf.Single "subType")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 4)
                (HsProtobuf.Prim HsProtobuf.UInt64)
                (HsProtobuf.Single "consumer_id")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 5)
                (HsProtobuf.Prim HsProtobuf.String)
                (HsProtobuf.Single "consumer_name")
                []
                "")]
 
instance HsJSONPB.ToJSONPB CommandSubscribe where
        toJSONPB (CommandSubscribe f1 f2 f3 f4 f5)
          = (HsJSONPB.object
               ["topic" .= f1, "subscription" .= f2, "subType" .= f3,
                "consumer_id" .= f4, "consumer_name" .= f5])
        toEncodingPB (CommandSubscribe f1 f2 f3 f4 f5)
          = (HsJSONPB.pairs
               ["topic" .= f1, "subscription" .= f2, "subType" .= f3,
                "consumer_id" .= f4, "consumer_name" .= f5])
 
instance HsJSONPB.FromJSONPB CommandSubscribe where
        parseJSONPB
          = (HsJSONPB.withObject "CommandSubscribe"
               (\ obj ->
                  (Hs.pure CommandSubscribe) <*> obj .: "topic" <*>
                    obj .: "subscription"
                    <*> obj .: "subType"
                    <*> obj .: "consumer_id"
                    <*> obj .: "consumer_name"))
 
instance HsJSONPB.ToJSON CommandSubscribe where
        toJSON = HsJSONPB.toAesonValue
        toEncoding = HsJSONPB.toAesonEncoding
 
instance HsJSONPB.FromJSON CommandSubscribe where
        parseJSON = HsJSONPB.parseJSONPB
 
instance HsJSONPB.ToSchema CommandSubscribe where
        declareNamedSchema _
          = do let declare_topic = HsJSONPB.declareSchemaRef
               commandSubscribeTopic <- declare_topic Proxy.Proxy
               let declare_subscription = HsJSONPB.declareSchemaRef
               commandSubscribeSubscription <- declare_subscription Proxy.Proxy
               let declare_subType = HsJSONPB.declareSchemaRef
               commandSubscribeSubType <- declare_subType Proxy.Proxy
               let declare_consumer_id = HsJSONPB.declareSchemaRef
               commandSubscribeConsumerId <- declare_consumer_id Proxy.Proxy
               let declare_consumer_name = HsJSONPB.declareSchemaRef
               commandSubscribeConsumerName <- declare_consumer_name Proxy.Proxy
               let _ = Hs.pure CommandSubscribe <*> HsJSONPB.asProxy declare_topic
                         <*> HsJSONPB.asProxy declare_subscription
                         <*> HsJSONPB.asProxy declare_subType
                         <*> HsJSONPB.asProxy declare_consumer_id
                         <*> HsJSONPB.asProxy declare_consumer_name
               Hs.return
                 (HsJSONPB.NamedSchema{HsJSONPB._namedSchemaName =
                                         Hs.Just "CommandSubscribe",
                                       HsJSONPB._namedSchemaSchema =
                                         Hs.mempty{HsJSONPB._schemaParamSchema =
                                                     Hs.mempty{HsJSONPB._paramSchemaType =
                                                                 Hs.Just HsJSONPB.SwaggerObject},
                                                   HsJSONPB._schemaProperties =
                                                     HsJSONPB.insOrdFromList
                                                       [("topic", commandSubscribeTopic),
                                                        ("subscription",
                                                         commandSubscribeSubscription),
                                                        ("subType", commandSubscribeSubType),
                                                        ("consumer_id", commandSubscribeConsumerId),
                                                        ("consumer_name",
                                                         commandSubscribeConsumerName)]}})
 
data CommandSubscribe_SubType = CommandSubscribe_SubTypeExclusive
                              | CommandSubscribe_SubTypeShared
                              deriving (Hs.Show, Hs.Eq, Hs.Generic, Hs.NFData)
 
instance HsProtobuf.Named CommandSubscribe_SubType where
        nameOf _ = (Hs.fromString "CommandSubscribe_SubType")
 
instance HsProtobuf.HasDefault CommandSubscribe_SubType
 
instance Hs.Bounded CommandSubscribe_SubType where
        minBound = CommandSubscribe_SubTypeExclusive
        maxBound = CommandSubscribe_SubTypeShared
 
instance Hs.Ord CommandSubscribe_SubType where
        compare x y
          = Hs.compare (HsProtobuf.fromProtoEnum x)
              (HsProtobuf.fromProtoEnum y)
 
instance HsProtobuf.ProtoEnum CommandSubscribe_SubType where
        toProtoEnumMay 0 = Hs.Just CommandSubscribe_SubTypeExclusive
        toProtoEnumMay 1 = Hs.Just CommandSubscribe_SubTypeShared
        toProtoEnumMay _ = Hs.Nothing
        fromProtoEnum (CommandSubscribe_SubTypeExclusive) = 0
        fromProtoEnum (CommandSubscribe_SubTypeShared) = 1
 
instance HsJSONPB.ToJSONPB CommandSubscribe_SubType where
        toJSONPB x _ = HsJSONPB.enumFieldString x
        toEncodingPB x _ = HsJSONPB.enumFieldEncoding x
 
instance HsJSONPB.FromJSONPB CommandSubscribe_SubType where
        parseJSONPB (HsJSONPB.String "Exclusive")
          = Hs.pure CommandSubscribe_SubTypeExclusive
        parseJSONPB (HsJSONPB.String "Shared")
          = Hs.pure CommandSubscribe_SubTypeShared
        parseJSONPB v
          = (HsJSONPB.typeMismatch "CommandSubscribe_SubType" v)
 
instance HsJSONPB.ToJSON CommandSubscribe_SubType where
        toJSON = HsJSONPB.toAesonValue
        toEncoding = HsJSONPB.toAesonEncoding
 
instance HsJSONPB.FromJSON CommandSubscribe_SubType where
        parseJSON = HsJSONPB.parseJSONPB
 
instance HsProtobuf.Finite CommandSubscribe_SubType
 
newtype CommandSubscribeSuccess = CommandSubscribeSuccess{commandSubscribeSuccessConsumerName
                                                          :: Hs.Text}
                                  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic, Hs.NFData)
 
instance HsProtobuf.Named CommandSubscribeSuccess where
        nameOf _ = (Hs.fromString "CommandSubscribeSuccess")
 
instance HsProtobuf.HasDefault CommandSubscribeSuccess
 
instance HsProtobuf.Message CommandSubscribeSuccess where
        encodeMessage _
          CommandSubscribeSuccess{commandSubscribeSuccessConsumerName =
                                    commandSubscribeSuccessConsumerName}
          = (Hs.mconcat
               [(HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 1)
                   commandSubscribeSuccessConsumerName)])
        decodeMessage _
          = (Hs.pure CommandSubscribeSuccess) <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 1))
        dotProto _
          = [(HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 1)
                (HsProtobuf.Prim HsProtobuf.String)
                (HsProtobuf.Single "consumer_name")
                []
                "")]
 
instance HsJSONPB.ToJSONPB CommandSubscribeSuccess where
        toJSONPB (CommandSubscribeSuccess f1)
          = (HsJSONPB.object ["consumer_name" .= f1])
        toEncodingPB (CommandSubscribeSuccess f1)
          = (HsJSONPB.pairs ["consumer_name" .= f1])
 
instance HsJSONPB.FromJSONPB CommandSubscribeSuccess where
        parseJSONPB
          = (HsJSONPB.withObject "CommandSubscribeSuccess"
               (\ obj ->
                  (Hs.pure CommandSubscribeSuccess) <*> obj .: "consumer_name"))
 
instance HsJSONPB.ToJSON CommandSubscribeSuccess where
        toJSON = HsJSONPB.toAesonValue
        toEncoding = HsJSONPB.toAesonEncoding
 
instance HsJSONPB.FromJSON CommandSubscribeSuccess where
        parseJSON = HsJSONPB.parseJSONPB
 
instance HsJSONPB.ToSchema CommandSubscribeSuccess where
        declareNamedSchema _
          = do let declare_consumer_name = HsJSONPB.declareSchemaRef
               commandSubscribeSuccessConsumerName <- declare_consumer_name
                                                        Proxy.Proxy
               let _ = Hs.pure CommandSubscribeSuccess <*>
                         HsJSONPB.asProxy declare_consumer_name
               Hs.return
                 (HsJSONPB.NamedSchema{HsJSONPB._namedSchemaName =
                                         Hs.Just "CommandSubscribeSuccess",
                                       HsJSONPB._namedSchemaSchema =
                                         Hs.mempty{HsJSONPB._schemaParamSchema =
                                                     Hs.mempty{HsJSONPB._paramSchemaType =
                                                                 Hs.Just HsJSONPB.SwaggerObject},
                                                   HsJSONPB._schemaProperties =
                                                     HsJSONPB.insOrdFromList
                                                       [("consumer_name",
                                                         commandSubscribeSuccessConsumerName)]}})
 
data CommandSuccess = CommandSuccess{}
                    deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic, Hs.NFData)
 
instance HsProtobuf.Named CommandSuccess where
        nameOf _ = (Hs.fromString "CommandSuccess")
 
instance HsProtobuf.HasDefault CommandSuccess
 
instance HsProtobuf.Message CommandSuccess where
        encodeMessage _ CommandSuccess{} = (Hs.mconcat [])
        decodeMessage _ = (Hs.pure CommandSuccess)
        dotProto _ = []
 
instance HsJSONPB.ToJSONPB CommandSuccess where
        toJSONPB (CommandSuccess) = (HsJSONPB.object [])
        toEncodingPB (CommandSuccess) = (HsJSONPB.pairs [])
 
instance HsJSONPB.FromJSONPB CommandSuccess where
        parseJSONPB
          = (HsJSONPB.withObject "CommandSuccess"
               (\ obj -> (Hs.pure CommandSuccess)))
 
instance HsJSONPB.ToJSON CommandSuccess where
        toJSON = HsJSONPB.toAesonValue
        toEncoding = HsJSONPB.toAesonEncoding
 
instance HsJSONPB.FromJSON CommandSuccess where
        parseJSON = HsJSONPB.parseJSONPB
 
instance HsJSONPB.ToSchema CommandSuccess where
        declareNamedSchema _
          = do Hs.return
                 (HsJSONPB.NamedSchema{HsJSONPB._namedSchemaName =
                                         Hs.Just "CommandSuccess",
                                       HsJSONPB._namedSchemaSchema =
                                         Hs.mempty{HsJSONPB._schemaParamSchema =
                                                     Hs.mempty{HsJSONPB._paramSchemaType =
                                                                 Hs.Just HsJSONPB.SwaggerObject},
                                                   HsJSONPB._schemaProperties =
                                                     HsJSONPB.insOrdFromList []}})
 
newtype CommandReceive = CommandReceive{commandReceiveConsumerId ::
                                        Hs.Word64}
                         deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic, Hs.NFData)
 
instance HsProtobuf.Named CommandReceive where
        nameOf _ = (Hs.fromString "CommandReceive")
 
instance HsProtobuf.HasDefault CommandReceive
 
instance HsProtobuf.Message CommandReceive where
        encodeMessage _
          CommandReceive{commandReceiveConsumerId = commandReceiveConsumerId}
          = (Hs.mconcat
               [(HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 1)
                   commandReceiveConsumerId)])
        decodeMessage _
          = (Hs.pure CommandReceive) <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 1))
        dotProto _
          = [(HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 1)
                (HsProtobuf.Prim HsProtobuf.UInt64)
                (HsProtobuf.Single "consumer_id")
                []
                "")]
 
instance HsJSONPB.ToJSONPB CommandReceive where
        toJSONPB (CommandReceive f1)
          = (HsJSONPB.object ["consumer_id" .= f1])
        toEncodingPB (CommandReceive f1)
          = (HsJSONPB.pairs ["consumer_id" .= f1])
 
instance HsJSONPB.FromJSONPB CommandReceive where
        parseJSONPB
          = (HsJSONPB.withObject "CommandReceive"
               (\ obj -> (Hs.pure CommandReceive) <*> obj .: "consumer_id"))
 
instance HsJSONPB.ToJSON CommandReceive where
        toJSON = HsJSONPB.toAesonValue
        toEncoding = HsJSONPB.toAesonEncoding
 
instance HsJSONPB.FromJSON CommandReceive where
        parseJSON = HsJSONPB.parseJSONPB
 
instance HsJSONPB.ToSchema CommandReceive where
        declareNamedSchema _
          = do let declare_consumer_id = HsJSONPB.declareSchemaRef
               commandReceiveConsumerId <- declare_consumer_id Proxy.Proxy
               let _ = Hs.pure CommandReceive <*>
                         HsJSONPB.asProxy declare_consumer_id
               Hs.return
                 (HsJSONPB.NamedSchema{HsJSONPB._namedSchemaName =
                                         Hs.Just "CommandReceive",
                                       HsJSONPB._namedSchemaSchema =
                                         Hs.mempty{HsJSONPB._schemaParamSchema =
                                                     Hs.mempty{HsJSONPB._paramSchemaType =
                                                                 Hs.Just HsJSONPB.SwaggerObject},
                                                   HsJSONPB._schemaProperties =
                                                     HsJSONPB.insOrdFromList
                                                       [("consumer_id",
                                                         commandReceiveConsumerId)]}})
 
data CommandRecord = CommandRecord{commandRecordConsumerId ::
                                   Hs.Word64,
                                   commandRecordPayload :: Hs.ByteString}
                   deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic, Hs.NFData)
 
instance HsProtobuf.Named CommandRecord where
        nameOf _ = (Hs.fromString "CommandRecord")
 
instance HsProtobuf.HasDefault CommandRecord
 
instance HsProtobuf.Message CommandRecord where
        encodeMessage _
          CommandRecord{commandRecordConsumerId = commandRecordConsumerId,
                        commandRecordPayload = commandRecordPayload}
          = (Hs.mconcat
               [(HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 1)
                   commandRecordConsumerId),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 2)
                   commandRecordPayload)])
        decodeMessage _
          = (Hs.pure CommandRecord) <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 1))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 2))
        dotProto _
          = [(HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 1)
                (HsProtobuf.Prim HsProtobuf.UInt64)
                (HsProtobuf.Single "consumer_id")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 2)
                (HsProtobuf.Prim HsProtobuf.Bytes)
                (HsProtobuf.Single "payload")
                []
                "")]
 
instance HsJSONPB.ToJSONPB CommandRecord where
        toJSONPB (CommandRecord f1 f2)
          = (HsJSONPB.object ["consumer_id" .= f1, "payload" .= f2])
        toEncodingPB (CommandRecord f1 f2)
          = (HsJSONPB.pairs ["consumer_id" .= f1, "payload" .= f2])
 
instance HsJSONPB.FromJSONPB CommandRecord where
        parseJSONPB
          = (HsJSONPB.withObject "CommandRecord"
               (\ obj ->
                  (Hs.pure CommandRecord) <*> obj .: "consumer_id" <*>
                    obj .: "payload"))
 
instance HsJSONPB.ToJSON CommandRecord where
        toJSON = HsJSONPB.toAesonValue
        toEncoding = HsJSONPB.toAesonEncoding
 
instance HsJSONPB.FromJSON CommandRecord where
        parseJSON = HsJSONPB.parseJSONPB
 
instance HsJSONPB.ToSchema CommandRecord where
        declareNamedSchema _
          = do let declare_consumer_id = HsJSONPB.declareSchemaRef
               commandRecordConsumerId <- declare_consumer_id Proxy.Proxy
               let declare_payload = HsJSONPB.declareSchemaRef
               commandRecordPayload <- declare_payload Proxy.Proxy
               let _ = Hs.pure CommandRecord <*>
                         HsJSONPB.asProxy declare_consumer_id
                         <*> HsJSONPB.asProxy declare_payload
               Hs.return
                 (HsJSONPB.NamedSchema{HsJSONPB._namedSchemaName =
                                         Hs.Just "CommandRecord",
                                       HsJSONPB._namedSchemaSchema =
                                         Hs.mempty{HsJSONPB._schemaParamSchema =
                                                     Hs.mempty{HsJSONPB._paramSchemaType =
                                                                 Hs.Just HsJSONPB.SwaggerObject},
                                                   HsJSONPB._schemaProperties =
                                                     HsJSONPB.insOrdFromList
                                                       [("consumer_id", commandRecordConsumerId),
                                                        ("payload", commandRecordPayload)]}})
 
data CommandAck = CommandAck{commandAckConsumerId :: Hs.Word64,
                             commandAckRecordId :: Hs.Word64}
                deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic, Hs.NFData)
 
instance HsProtobuf.Named CommandAck where
        nameOf _ = (Hs.fromString "CommandAck")
 
instance HsProtobuf.HasDefault CommandAck
 
instance HsProtobuf.Message CommandAck where
        encodeMessage _
          CommandAck{commandAckConsumerId = commandAckConsumerId,
                     commandAckRecordId = commandAckRecordId}
          = (Hs.mconcat
               [(HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 1)
                   commandAckConsumerId),
                (HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 2)
                   commandAckRecordId)])
        decodeMessage _
          = (Hs.pure CommandAck) <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 1))
              <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 2))
        dotProto _
          = [(HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 1)
                (HsProtobuf.Prim HsProtobuf.UInt64)
                (HsProtobuf.Single "consumer_id")
                []
                ""),
             (HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 2)
                (HsProtobuf.Prim HsProtobuf.UInt64)
                (HsProtobuf.Single "record_id")
                []
                "")]
 
instance HsJSONPB.ToJSONPB CommandAck where
        toJSONPB (CommandAck f1 f2)
          = (HsJSONPB.object ["consumer_id" .= f1, "record_id" .= f2])
        toEncodingPB (CommandAck f1 f2)
          = (HsJSONPB.pairs ["consumer_id" .= f1, "record_id" .= f2])
 
instance HsJSONPB.FromJSONPB CommandAck where
        parseJSONPB
          = (HsJSONPB.withObject "CommandAck"
               (\ obj ->
                  (Hs.pure CommandAck) <*> obj .: "consumer_id" <*>
                    obj .: "record_id"))
 
instance HsJSONPB.ToJSON CommandAck where
        toJSON = HsJSONPB.toAesonValue
        toEncoding = HsJSONPB.toAesonEncoding
 
instance HsJSONPB.FromJSON CommandAck where
        parseJSON = HsJSONPB.parseJSONPB
 
instance HsJSONPB.ToSchema CommandAck where
        declareNamedSchema _
          = do let declare_consumer_id = HsJSONPB.declareSchemaRef
               commandAckConsumerId <- declare_consumer_id Proxy.Proxy
               let declare_record_id = HsJSONPB.declareSchemaRef
               commandAckRecordId <- declare_record_id Proxy.Proxy
               let _ = Hs.pure CommandAck <*> HsJSONPB.asProxy declare_consumer_id
                         <*> HsJSONPB.asProxy declare_record_id
               Hs.return
                 (HsJSONPB.NamedSchema{HsJSONPB._namedSchemaName =
                                         Hs.Just "CommandAck",
                                       HsJSONPB._namedSchemaSchema =
                                         Hs.mempty{HsJSONPB._schemaParamSchema =
                                                     Hs.mempty{HsJSONPB._paramSchemaType =
                                                                 Hs.Just HsJSONPB.SwaggerObject},
                                                   HsJSONPB._schemaProperties =
                                                     HsJSONPB.insOrdFromList
                                                       [("consumer_id", commandAckConsumerId),
                                                        ("record_id", commandAckRecordId)]}})
 
newtype CommandCloseConsumer = CommandCloseConsumer{commandCloseConsumerConsumerId
                                                    :: Hs.Word64}
                               deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic, Hs.NFData)
 
instance HsProtobuf.Named CommandCloseConsumer where
        nameOf _ = (Hs.fromString "CommandCloseConsumer")
 
instance HsProtobuf.HasDefault CommandCloseConsumer
 
instance HsProtobuf.Message CommandCloseConsumer where
        encodeMessage _
          CommandCloseConsumer{commandCloseConsumerConsumerId =
                                 commandCloseConsumerConsumerId}
          = (Hs.mconcat
               [(HsProtobuf.encodeMessageField (HsProtobuf.FieldNumber 1)
                   commandCloseConsumerConsumerId)])
        decodeMessage _
          = (Hs.pure CommandCloseConsumer) <*>
              (HsProtobuf.at HsProtobuf.decodeMessageField
                 (HsProtobuf.FieldNumber 1))
        dotProto _
          = [(HsProtobuf.DotProtoField (HsProtobuf.FieldNumber 1)
                (HsProtobuf.Prim HsProtobuf.UInt64)
                (HsProtobuf.Single "consumer_id")
                []
                "")]
 
instance HsJSONPB.ToJSONPB CommandCloseConsumer where
        toJSONPB (CommandCloseConsumer f1)
          = (HsJSONPB.object ["consumer_id" .= f1])
        toEncodingPB (CommandCloseConsumer f1)
          = (HsJSONPB.pairs ["consumer_id" .= f1])
 
instance HsJSONPB.FromJSONPB CommandCloseConsumer where
        parseJSONPB
          = (HsJSONPB.withObject "CommandCloseConsumer"
               (\ obj -> (Hs.pure CommandCloseConsumer) <*> obj .: "consumer_id"))
 
instance HsJSONPB.ToJSON CommandCloseConsumer where
        toJSON = HsJSONPB.toAesonValue
        toEncoding = HsJSONPB.toAesonEncoding
 
instance HsJSONPB.FromJSON CommandCloseConsumer where
        parseJSON = HsJSONPB.parseJSONPB
 
instance HsJSONPB.ToSchema CommandCloseConsumer where
        declareNamedSchema _
          = do let declare_consumer_id = HsJSONPB.declareSchemaRef
               commandCloseConsumerConsumerId <- declare_consumer_id Proxy.Proxy
               let _ = Hs.pure CommandCloseConsumer <*>
                         HsJSONPB.asProxy declare_consumer_id
               Hs.return
                 (HsJSONPB.NamedSchema{HsJSONPB._namedSchemaName =
                                         Hs.Just "CommandCloseConsumer",
                                       HsJSONPB._namedSchemaSchema =
                                         Hs.mempty{HsJSONPB._schemaParamSchema =
                                                     Hs.mempty{HsJSONPB._paramSchemaType =
                                                                 Hs.Just HsJSONPB.SwaggerObject},
                                                   HsJSONPB._schemaProperties =
                                                     HsJSONPB.insOrdFromList
                                                       [("consumer_id",
                                                         commandCloseConsumerConsumerId)]}})